name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Run Eslint
        run: pnpm lint
