name: CI
description: 'Run linting and tests'

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI Setup Action
        uses: ./.github/actions/ci-setup

      - name: Run Eslint
        run: pnpm lint
