name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    paths:
      - 'src/*.{js, jsx, ts, tsx}'
      - 'src/**/*.{js, jsx, ts, tsx}'
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI Setup Action
        uses: ./.github/actions/ci-setup
        with:
          pnpm-version: 10.3.0
          node-version: 22.13.1

      - name: Run Eslint
        run: pnpm lint
